"""
Django settings for alice_masterclass_django project.

Generated by 'django-admin startproject' using Django 3.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import os
import requests
import json
from datetime import timedelta
from rest_framework import status

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-d@sohzq%*(9-g)%9zrkrau+d348@ao0b4d-5=gr49jq1uvki8t')

DJANGO_LOCAL = int(os.getenv('DJANGO_LOCAL', 0)) == 1
_use_production_env = bool(os.getenv('ALLOWED_HOSTS') and os.getenv('CORS_ALLOWED_ORIGINS'))
# Enable dummy auth when local or when production env not configured (avoids 401 for local dev)
DJANGO_DUMMY_AUTH = int(os.getenv('DJANGO_DUMMY_AUTH', 1 if not _use_production_env else 0)) == 1

# SECURITY WARNING: don't run with debug turned on in production!
if DJANGO_LOCAL == 1 or not _use_production_env:
    DEBUG = True
    CORS_ALLOW_ALL_ORIGINS = True
    if not _use_production_env:
        ALLOWED_HOSTS = ['localhost', '127.0.0.1']
else:
    ALLOWED_HOSTS = [h.strip() for h in os.getenv('ALLOWED_HOSTS').split(',')]
    CORS_ALLOWED_ORIGINS = [o.strip() for o in os.getenv('CORS_ALLOWED_ORIGINS').split(',')]

# Auto-configure settings based on data returned by the well-known endpoint
WELL_KNOWN_URL = os.getenv('WELL_KNOWN_URL', 'https://auth.cern.ch/auth/realms/cern/.well-known/openid-configuration')
AUTH_URL = 'https://auth.cern.ch/auth/realms/cern/protocol/openid-connect/auth'
LOGIN_URL = 'https://auth.cern.ch/auth/realms/cern/protocol/openid-connect/token'
LOGOUT_URL = 'https://auth.cern.ch/auth/realms/cern/protocol/openid-connect/logout'
INFO_URL = 'https://auth.cern.ch/auth/realms/cern/account'

# Skip CERN auth fetch when running locally (avoids proxy/network errors outside CERN)
_skip_cern_fetch = not _use_production_env or (DJANGO_LOCAL and DJANGO_DUMMY_AUTH)
if not _skip_cern_fetch:
    r = requests.get(WELL_KNOWN_URL)
    if r.status_code == status.HTTP_200_OK:
        data = json.loads(r.text)
        AUTH_URL = data['authorization_endpoint']
        LOGIN_URL = data['token_endpoint']
        LOGOUT_URL = data['end_session_endpoint']
        INFO_URL = data['userinfo_endpoint']

REDIRECT_URI = os.getenv('REDIRECT_URI', 'http://localhost:8000/oauth')
CLIENT_ID = os.getenv('CLIENT_ID', 'webframeworks-paas-alice-masterclass2')
CLIENT_SECRET = os.getenv('CLIENT_SECRET', '7b051f9c-3c07-4a30-9bd1-83a491c504bf')
FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:4201/login')

# Expiration time for the access tokens
TOKEN_EXPIRATION_TIME = timedelta(hours=12)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
    'loggers': {
        'masterclass_error': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': True
        }
    }
}

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'django_fullclean',
    'masterclass.apps.MasterclassConfig',
    'strangeness.apps.StrangenessConfig'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'alice_masterclass_django.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'alice_masterclass_django.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

if DJANGO_LOCAL or not _use_production_env:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': str(BASE_DIR / 'masterclass.sqlite')
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': os.getenv('DATABASE_NAME'),
            'USER': os.getenv('DATABASE_USER'),
            'PASSWORD': os.getenv('DATABASE_PASSWORD'),
            'HOST': os.getenv('SERVICE_HOST'),
            'PORT': os.getenv('SERVICE_PORT')
        }
    }
# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny'
    ]
}


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
