# Generated by Django 3.2.4 on 2026-02-28 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterclass', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LargeScaleAnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.PositiveIntegerField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterclass.session')),
            ],
        ),
        migrations.CreateModel(
            name='VisualAnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.PositiveIntegerField()),
                ('dataset', models.IntegerField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterclass.session')),
            ],
        ),
        migrations.CreateModel(
            name='VisualAnalysisResultsEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventid', models.PositiveIntegerField()),
                ('particle', models.CharField(choices=[('k0', 'Kaon'), ('lambda', 'Lambda'), ('antilambda', 'Anti-Lambda'), ('xi', 'xi')], max_length=16)),
                ('mass', models.FloatField()),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strangeness.visualanalysisresult')),
            ],
        ),
        migrations.CreateModel(
            name='LargeScaleAnalysisResultsEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('particle', models.CharField(choices=[('k0', 'Kaon'), ('lambda', 'Lambda'), ('antilambda', 'Anti-Lambda'), ('xi', 'xi')], max_length=16)),
                ('collision', models.CharField(choices=[('pp', 'pp'), ('pbpb', 'Pb-Pb')], max_length=4)),
                ('centrality', models.CharField(choices=[('000_000', '0%'), ('000_010', '0% - 10%'), ('010_020', '10% - 20%'), ('020_030', '20% - 30%'), ('030_040', '30% - 40%'), ('040_050', '40% - 50%'), ('050_060', '50% - 60%'), ('060_070', '60% - 70%'), ('070_080', '70% - 80%'), ('080_090', '80% - 90%'), ('090_100', '90% - 100%')], max_length=7)),
                ('signal', models.PositiveIntegerField()),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strangeness.largescaleanalysisresult')),
            ],
        ),
        migrations.AddConstraint(
            model_name='visualanalysisresultsentry',
            constraint=models.UniqueConstraint(fields=('result', 'eventid'), name='vare_u_fields'),
        ),
        migrations.AddConstraint(
            model_name='visualanalysisresult',
            constraint=models.UniqueConstraint(fields=('session', 'student', 'dataset'), name='var_u_fields'),
        ),
        migrations.AddConstraint(
            model_name='largescaleanalysisresultsentry',
            constraint=models.UniqueConstraint(fields=('result', 'particle', 'collision', 'centrality'), name='lsare_u_fields'),
        ),
        migrations.AddConstraint(
            model_name='largescaleanalysisresult',
            constraint=models.UniqueConstraint(fields=('session', 'student'), name='lsar_u_fields'),
        ),
    ]
